// Полный список всех 114 сур Корана
export interface Surah {
  number: number
  title: string
  arabic: string
  url: string
  transliteration: string
  englishTitle: string
  uzbekTitle: string
  verses: number
}

export const surahs: Surah[] = [
  {
    number: 1,
    title: "Аль-Фатиха",
    arabic: "ٱلْفَاتِحَة",
    url: "/audio/001_al_fatiha.mp3",
    transliteration: "Al-Fatiha",
    englishTitle: "The Opening",
    uzbekTitle: "Fotiha",
    verses: 7,
  },
  {
    number: 2,
    title: "Аль-Бакара",
    arabic: "ٱلْبَقَرَة",
    url: "/audio/002_al_baqarah.mp3",
    transliteration: "Al-Baqarah",
    englishTitle: "The Cow",
    uzbekTitle: "Baqara",
    verses: 286,
  },
  {
    number: 3,
    title: "Али Имран",
    arabic: "آل عِمْرَان",
    url: "/audio/003_ali_imran.mp3",
    transliteration: "Ali Imran",
    englishTitle: "The Family of Imran",
    uzbekTitle: "Oli Imron",
    verses: 200,
  },
  {
    number: 4,
    title: "Ан-Ниса",
    arabic: "ٱلنِّسَاء",
    url: "/audio/004_an_nisa.mp3",
    transliteration: "An-Nisa",
    englishTitle: "The Women",
    uzbekTitle: "Niso",
    verses: 176,
  },
  {
    number: 5,
    title: "Аль-Маида",
    arabic: "ٱلْمَائِدَة",
    url: "/audio/005_al_maida.mp3",
    transliteration: "Al-Ma'ida",
    englishTitle: "The Table",
    uzbekTitle: "Moida",
    verses: 120,
  },
  {
    number: 6,
    title: "Аль-Анам",
    arabic: "ٱلْأَنْعَام",
    url: "/audio/006_al_anam.mp3",
    transliteration: "Al-An'am",
    englishTitle: "The Cattle",
    uzbekTitle: "An'om",
    verses: 165,
  },
  {
    number: 7,
    title: "Аль-Араф",
    arabic: "ٱلْأَعْرَاف",
    url: "/audio/007_al_araf.mp3",
    transliteration: "Al-A'raf",
    englishTitle: "The Heights",
    uzbekTitle: "A'rof",
    verses: 206,
  },
  {
    number: 8,
    title: "Аль-Анфаль",
    arabic: "ٱلْأَنْفَال",
    url: "/audio/008_al_anfal.mp3",
    transliteration: "Al-Anfal",
    englishTitle: "The Spoils of War",
    uzbekTitle: "Anfol",
    verses: 75,
  },
  {
    number: 9,
    title: "Ат-Тауба",
    arabic: "ٱلتَّوْبَة",
    url: "/audio/009_at_tawbah.mp3",
    transliteration: "At-Tawbah",
    englishTitle: "The Repentance",
    uzbekTitle: "Tavba",
    verses: 129,
  },
  {
    number: 10,
    title: "Юнус",
    arabic: "يُونُس",
    url: "/audio/010_yunus.mp3",
    transliteration: "Yunus",
    englishTitle: "Jonah",
    uzbekTitle: "Yunus",
    verses: 109,
  },
  {
    number: 11,
    title: "Худ",
    arabic: "هُود",
    url: "/audio/011_hud.mp3",
    transliteration: "Hud",
    englishTitle: "Hud",
    uzbekTitle: "Hud",
    verses: 123,
  },
  {
    number: 12,
    title: "Юсуф",
    arabic: "يُوسُف",
    url: "/audio/012_yusuf.mp3",
    transliteration: "Yusuf",
    englishTitle: "Joseph",
    uzbekTitle: "Yusuf",
    verses: 111,
  },
  {
    number: 13,
    title: "Ар-Рад",
    arabic: "ٱلرَّعْد",
    url: "/audio/013_ar_rad.mp3",
    transliteration: "Ar-Ra'd",
    englishTitle: "The Thunder",
    uzbekTitle: "Ra'd",
    verses: 43,
  },
  {
    number: 14,
    title: "Ибрахим",
    arabic: "إِبْرَاهِيم",
    url: "/audio/014_ibrahim.mp3",
    transliteration: "Ibrahim",
    englishTitle: "Abraham",
    uzbekTitle: "Ibrohim",
    verses: 52,
  },
  {
    number: 15,
    title: "Аль-Хиджр",
    arabic: "ٱلْحِجْر",
    url: "/audio/015_al_hijr.mp3",
    transliteration: "Al-Hijr",
    englishTitle: "The Rocky Tract",
    uzbekTitle: "Hijr",
    verses: 99,
  },
  {
    number: 16,
    title: "Ан-Нахль",
    arabic: "ٱلنَّحْل",
    url: "/audio/016_an_nahl.mp3",
    transliteration: "An-Nahl",
    englishTitle: "The Bee",
    uzbekTitle: "Nahl",
    verses: 128,
  },
  {
    number: 17,
    title: "Аль-Исра",
    arabic: "ٱلْإِسْرَاء",
    url: "/audio/017_al_isra.mp3",
    transliteration: "Al-Isra",
    englishTitle: "The Night Journey",
    uzbekTitle: "Isro",
    verses: 111,
  },
  {
    number: 18,
    title: "Аль-Кахф",
    arabic: "ٱلْكَهْف",
    url: "/audio/018_al_kahf.mp3",
    transliteration: "Al-Kahf",
    englishTitle: "The Cave",
    uzbekTitle: "Kahf",
    verses: 110,
  },
  {
    number: 19,
    title: "Марьям",
    arabic: "مَرْيَم",
    url: "/audio/019_maryam.mp3",
    transliteration: "Maryam",
    englishTitle: "Mary",
    uzbekTitle: "Maryam",
    verses: 98,
  },
  {
    number: 20,
    title: "Та-Ха",
    arabic: "طه",
    url: "/audio/020_ta_ha.mp3",
    transliteration: "Ta-Ha",
    englishTitle: "Ta-Ha",
    uzbekTitle: "Toho",
    verses: 135,
  },
  {
    number: 21,
    title: "Аль-Анбия",
    arabic: "ٱلْأَنْبِيَاء",
    url: "/audio/021_al_anbiya.mp3",
    transliteration: "Al-Anbiya",
    englishTitle: "The Prophets",
    uzbekTitle: "Anbiyo",
    verses: 112,
  },
  {
    number: 22,
    title: "Аль-Хадж",
    arabic: "ٱلْحَجّ",
    url: "/audio/022_al_hajj.mp3",
    transliteration: "Al-Hajj",
    englishTitle: "The Pilgrimage",
    uzbekTitle: "Haj",
    verses: 78,
  },
  {
    number: 23,
    title: "Аль-Муминун",
    arabic: "ٱلْمُؤْمِنُون",
    url: "/audio/023_al_muminun.mp3",
    transliteration: "Al-Mu'minun",
    englishTitle: "The Believers",
    uzbekTitle: "Mo'minun",
    verses: 118,
  },
  {
    number: 24,
    title: "Ан-Нур",
    arabic: "ٱلنُّور",
    url: "/audio/024_an_nur.mp3",
    transliteration: "An-Nur",
    englishTitle: "The Light",
    uzbekTitle: "Nur",
    verses: 64,
  },
  {
    number: 25,
    title: "Аль-Фуркан",
    arabic: "ٱلْفُرْقَان",
    url: "/audio/025_al_furqan.mp3",
    transliteration: "Al-Furqan",
    englishTitle: "The Criterion",
    uzbekTitle: "Furqon",
    verses: 77,
  },
  {
    number: 26,
    title: "Аш-Шуара",
    arabic: "ٱلشُّعَرَاء",
    url: "/audio/026_ash_shuara.mp3",
    transliteration: "Ash-Shu'ara",
    englishTitle: "The Poets",
    uzbekTitle: "Shuaro",
    verses: 227,
  },
  {
    number: 27,
    title: "Ан-Намль",
    arabic: "ٱلنَّمْل",
    url: "/audio/027_an_naml.mp3",
    transliteration: "An-Naml",
    englishTitle: "The Ant",
    uzbekTitle: "Naml",
    verses: 93,
  },
  {
    number: 28,
    title: "Аль-Касас",
    arabic: "ٱلْقَصَص",
    url: "/audio/028_al_qasas.mp3",
    transliteration: "Al-Qasas",
    englishTitle: "The Stories",
    uzbekTitle: "Qasas",
    verses: 88,
  },
  {
    number: 29,
    title: "Аль-Анкабут",
    arabic: "ٱلْعَنْكَبُوت",
    url: "/audio/029_al_ankabut.mp3",
    transliteration: "Al-Ankabut",
    englishTitle: "The Spider",
    uzbekTitle: "Ankabut",
    verses: 69,
  },
  {
    number: 30,
    title: "Ар-Рум",
    arabic: "ٱلرُّوم",
    url: "/audio/030_ar_rum.mp3",
    transliteration: "Ar-Rum",
    englishTitle: "The Romans",
    uzbekTitle: "Rum",
    verses: 60,
  },
  {
    number: 31,
    title: "Лукман",
    arabic: "لُقْمَان",
    url: "/audio/031_luqman.mp3",
    transliteration: "Luqman",
    englishTitle: "Luqman",
    uzbekTitle: "Luqmon",
    verses: 34,
  },
  {
    number: 32,
    title: "Ас-Саджда",
    arabic: "ٱلسَّجْدَة",
    url: "/audio/032_as_sajda.mp3",
    transliteration: "As-Sajdah",
    englishTitle: "The Prostration",
    uzbekTitle: "Sajda",
    verses: 30,
  },
  {
    number: 33,
    title: "Аль-Ахзаб",
    arabic: "ٱلْأَحْزَاب",
    url: "/audio/033_al_ahzab.mp3",
    transliteration: "Al-Ahzab",
    englishTitle: "The Combined Forces",
    uzbekTitle: "Ahzob",
    verses: 73,
  },
  {
    number: 34,
    title: "Саба",
    arabic: "سَبَأ",
    url: "/audio/034_saba.mp3",
    transliteration: "Saba",
    englishTitle: "Sheba",
    uzbekTitle: "Saba",
    verses: 54,
  },
  {
    number: 35,
    title: "Фатир",
    arabic: "فَاطِر",
    url: "/audio/035_fatir.mp3",
    transliteration: "Fatir",
    englishTitle: "The Creator",
    uzbekTitle: "Fotir",
    verses: 45,
  },
  {
    number: 36,
    title: "Я Син",
    arabic: "يس",
    url: "/audio/036_ya_sin.mp3",
    transliteration: "Ya-Sin",
    englishTitle: "Ya-Sin",
    uzbekTitle: "Yosin",
    verses: 83,
  },
  {
    number: 37,
    title: "Ас-Саффат",
    arabic: "ٱلصَّافَّات",
    url: "/audio/037_as_saffat.mp3",
    transliteration: "As-Saffat",
    englishTitle: "Those Ranged in Ranks",
    uzbekTitle: "Soffot",
    verses: 182,
  },
  {
    number: 38,
    title: "Сад",
    arabic: "ص",
    url: "/audio/038_sad.mp3",
    transliteration: "Sad",
    englishTitle: "Sad",
    uzbekTitle: "Sod",
    verses: 88,
  },
  {
    number: 39,
    title: "Аз-Зумар",
    arabic: "ٱلزُّمَر",
    url: "/audio/039_az_zumar.mp3",
    transliteration: "Az-Zumar",
    englishTitle: "The Groups",
    uzbekTitle: "Zumar",
    verses: 75,
  },
  {
    number: 40,
    title: "Гафир",
    arabic: "غَافِر",
    url: "/audio/040_ghafir.mp3",
    transliteration: "Ghafir",
    englishTitle: "The Forgiver",
    uzbekTitle: "G'ofir",
    verses: 85,
  },
  {
    number: 41,
    title: "Фуссилат",
    arabic: "فُصِّلَت",
    url: "/audio/041_fussilat.mp3",
    transliteration: "Fussilat",
    englishTitle: "Distinguished",
    uzbekTitle: "Fussilat",
    verses: 54,
  },
  {
    number: 42,
    title: "Аш-Шура",
    arabic: "ٱلشُّورىٰ",
    url: "/audio/042_ash_shura.mp3",
    transliteration: "Ash-Shura",
    englishTitle: "The Consultation",
    uzbekTitle: "Shuro",
    verses: 53,
  },
  {
    number: 43,
    title: "Аз-Зухруф",
    arabic: "ٱلزُّخْرُف",
    url: "/audio/043_az_zukhruf.mp3",
    transliteration: "Az-Zukhruf",
    englishTitle: "The Gold",
    uzbekTitle: "Zuxruf",
    verses: 89,
  },
  {
    number: 44,
    title: "Ад-Духан",
    arabic: "ٱلدُّخَان",
    url: "/audio/044_ad_dukhan.mp3",
    transliteration: "Ad-Dukhan",
    englishTitle: "The Smoke",
    uzbekTitle: "Duxon",
    verses: 59,
  },
  {
    number: 45,
    title: "Аль-Джасия",
    arabic: "ٱلْجَاثِيَة",
    url: "/audio/045_al_jathiya.mp3",
    transliteration: "Al-Jathiyah",
    englishTitle: "The Kneeling",
    uzbekTitle: "Josiya",
    verses: 37,
  },
  {
    number: 46,
    title: "Аль-Ахкаф",
    arabic: "ٱلْأَحْقَاف",
    url: "/audio/046_al_ahqaf.mp3",
    transliteration: "Al-Ahqaf",
    englishTitle: "The Curved Sand-hills",
    uzbekTitle: "Ahqof",
    verses: 35,
  },
  {
    number: 47,
    title: "Мухаммад",
    arabic: "مُحَمَّد",
    url: "/audio/047_muhammad.mp3",
    transliteration: "Muhammad",
    englishTitle: "Muhammad",
    uzbekTitle: "Muhammad",
    verses: 38,
  },
  {
    number: 48,
    title: "Аль-Фатх",
    arabic: "ٱلْفَتْح",
    url: "/audio/048_al_fath.mp3",
    transliteration: "Al-Fath",
    englishTitle: "The Victory",
    uzbekTitle: "Fath",
    verses: 29,
  },
  {
    number: 49,
    title: "Аль-Худжурат",
    arabic: "ٱلْحُجُرَات",
    url: "/audio/049_al_hujurat.mp3",
    transliteration: "Al-Hujurat",
    englishTitle: "The Dwellings",
    uzbekTitle: "Hujurot",
    verses: 18,
  },
  {
    number: 50,
    title: "Каф",
    arabic: "ق",
    url: "/audio/050_qaf.mp3",
    transliteration: "Qaf",
    englishTitle: "Qaf",
    uzbekTitle: "Qof",
    verses: 45,
  },
  {
    number: 51,
    title: "Аз-Зарият",
    arabic: "ٱلذَّارِيَات",
    url: "/audio/051_az_zariyat.mp3",
    transliteration: "Az-Zariyat",
    englishTitle: "The Wind that Scatter",
    uzbekTitle: "Zoriyot",
    verses: 60,
  },
  {
    number: 52,
    title: "Ат-Тур",
    arabic: "ٱلطُّور",
    url: "/audio/052_at_tur.mp3",
    transliteration: "At-Tur",
    englishTitle: "The Mount",
    uzbekTitle: "Tur",
    verses: 49,
  },
  {
    number: 53,
    title: "Ан-Наджм",
    arabic: "ٱلنَّجْم",
    url: "/audio/053_an_najm.mp3",
    transliteration: "An-Najm",
    englishTitle: "The Star",
    uzbekTitle: "Najm",
    verses: 62,
  },
  {
    number: 54,
    title: "Аль-Камар",
    arabic: "ٱلْقَمَر",
    url: "/audio/054_al_qamar.mp3",
    transliteration: "Al-Qamar",
    englishTitle: "The Moon",
    uzbekTitle: "Qamar",
    verses: 55,
  },
  {
    number: 55,
    title: "Ар-Рахман",
    arabic: "ٱلرَّحْمَٰن",
    url: "/audio/055_ar_rahman.mp3",
    transliteration: "Ar-Rahman",
    englishTitle: "The Most Gracious",
    uzbekTitle: "Rahman",
    verses: 78,
  },
  {
    number: 56,
    title: "Аль-Вакиа",
    arabic: "ٱلْوَاقِعَة",
    url: "/audio/056_al_waqia.mp3",
    transliteration: "Al-Waqi'ah",
    englishTitle: "The Event",
    uzbekTitle: "Voqia",
    verses: 96,
  },
  {
    number: 57,
    title: "Аль-Хадид",
    arabic: "ٱلْحَدِيد",
    url: "/audio/057_al_hadid.mp3",
    transliteration: "Al-Hadid",
    englishTitle: "The Iron",
    uzbekTitle: "Hadid",
    verses: 29,
  },
  {
    number: 58,
    title: "Аль-Муджадала",
    arabic: "ٱلْمُجَادَلَة",
    url: "/audio/058_al_mujadala.mp3",
    transliteration: "Al-Mujadilah",
    englishTitle: "The Pleading",
    uzbekTitle: "Mujodala",
    verses: 22,
  },
  {
    number: 59,
    title: "Аль-Хашр",
    arabic: "ٱلْحَشْر",
    url: "/audio/059_al_hashr.mp3",
    transliteration: "Al-Hashr",
    englishTitle: "The Gathering",
    uzbekTitle: "Hashr",
    verses: 24,
  },
  {
    number: 60,
    title: "Аль-Мумтахана",
    arabic: "ٱلْمُمْتَحَنَة",
    url: "/audio/060_al_mumtahana.mp3",
    transliteration: "Al-Mumtahanah",
    englishTitle: "The Examined One",
    uzbekTitle: "Mumtahana",
    verses: 13,
  },
  {
    number: 61,
    title: "Ас-Сафф",
    arabic: "ٱلصَّفّ",
    url: "/audio/061_as_saff.mp3",
    transliteration: "As-Saff",
    englishTitle: "The Row",
    uzbekTitle: "Saff",
    verses: 14,
  },
  {
    number: 62,
    title: "Аль-Джумуа",
    arabic: "ٱلْجُمُعَة",
    url: "/audio/062_al_jumuah.mp3",
    transliteration: "Al-Jumu'ah",
    englishTitle: "Friday",
    uzbekTitle: "Juma",
    verses: 11,
  },
  {
    number: 63,
    title: "Аль-Мунафикун",
    arabic: "ٱلْمُنَافِقُون",
    url: "/audio/063_al_munafiqun.mp3",
    transliteration: "Al-Munafiqun",
    englishTitle: "The Hypocrites",
    uzbekTitle: "Munofiqun",
    verses: 11,
  },
  {
    number: 64,
    title: "Ат-Тагабун",
    arabic: "ٱلتَّغَابُن",
    url: "/audio/064_at_taghabun.mp3",
    transliteration: "At-Taghabun",
    englishTitle: "The Loss and Gain",
    uzbekTitle: "Tag'obun",
    verses: 18,
  },
  {
    number: 65,
    title: "Ат-Талак",
    arabic: "ٱلطَّلَاق",
    url: "/audio/065_at_talaq.mp3",
    transliteration: "At-Talaq",
    englishTitle: "The Divorce",
    uzbekTitle: "Taloq",
    verses: 12,
  },
  {
    number: 66,
    title: "Ат-Тахрим",
    arabic: "ٱلتَّحْرِيم",
    url: "/audio/066_at_tahrim.mp3",
    transliteration: "At-Tahrim",
    englishTitle: "The Prohibition",
    uzbekTitle: "Tahrim",
    verses: 12,
  },
  {
    number: 67,
    title: "Аль-Мульк",
    arabic: "ٱلْمُلْك",
    url: "/audio/067_al_mulk.mp3",
    transliteration: "Al-Mulk",
    englishTitle: "The Kingdom",
    uzbekTitle: "Mulk",
    verses: 30,
  },
  {
    number: 68,
    title: "Аль-Калам",
    arabic: "ٱلْقَلَم",
    url: "/audio/068_al_qalam.mp3",
    transliteration: "Al-Qalam",
    englishTitle: "The Pen",
    uzbekTitle: "Qalam",
    verses: 52,
  },
  {
    number: 69,
    title: "Аль-Хакка",
    arabic: "ٱلْحَاقَّة",
    url: "/audio/069_al_haqqa.mp3",
    transliteration: "Al-Haqqah",
    englishTitle: "The Inevitable",
    uzbekTitle: "Haqqa",
    verses: 52,
  },
  {
    number: 70,
    title: "Аль-Мааридж",
    arabic: "ٱلْمَعَارِج",
    url: "/audio/070_al_maarij.mp3",
    transliteration: "Al-Ma'arij",
    englishTitle: "The Ways of Ascent",
    uzbekTitle: "Ma'orij",
    verses: 44,
  },
  {
    number: 71,
    title: "Нух",
    arabic: "نُوح",
    url: "/audio/071_nuh.mp3",
    transliteration: "Nuh",
    englishTitle: "Noah",
    uzbekTitle: "Nuh",
    verses: 28,
  },
  {
    number: 72,
    title: "Аль-Джинн",
    arabic: "ٱلْجِنّ",
    url: "/audio/072_al_jinn.mp3",
    transliteration: "Al-Jinn",
    englishTitle: "The Jinn",
    uzbekTitle: "Jin",
    verses: 28,
  },
  {
    number: 73,
    title: "Аль-Муззаммиль",
    arabic: "ٱلْمُزَّمِّل",
    url: "/audio/073_al_muzzammil.mp3",
    transliteration: "Al-Muzzammil",
    englishTitle: "The Wrapped",
    uzbekTitle: "Muzzammil",
    verses: 20,
  },
  {
    number: 74,
    title: "Аль-Муддассир",
    arabic: "ٱلْمُدَّثِّر",
    url: "/audio/074_al_muddaththir.mp3",
    transliteration: "Al-Muddaththir",
    englishTitle: "The Cloaked",
    uzbekTitle: "Muddassir",
    verses: 56,
  },
  {
    number: 75,
    title: "Аль-Кияма",
    arabic: "ٱلْقِيَامَة",
    url: "/audio/075_al_qiyama.mp3",
    transliteration: "Al-Qiyamah",
    englishTitle: "The Resurrection",
    uzbekTitle: "Qiyoma",
    verses: 40,
  },
  {
    number: 76,
    title: "Аль-Инсан",
    arabic: "ٱلْإِنْسَان",
    url: "/audio/076_al_insan.mp3",
    transliteration: "Al-Insan",
    englishTitle: "The Human",
    uzbekTitle: "Inson",
    verses: 31,
  },
  {
    number: 77,
    title: "Аль-Мурсалат",
    arabic: "ٱلْمُرْسَلَات",
    url: "/audio/077_al_mursalat.mp3",
    transliteration: "Al-Mursalat",
    englishTitle: "Those Sent Forth",
    uzbekTitle: "Mursalot",
    verses: 50,
  },
  {
    number: 78,
    title: "Ан-Наба",
    arabic: "ٱلنَّبَأ",
    url: "/audio/078_an_naba.mp3",
    transliteration: "An-Naba",
    englishTitle: "The Great News",
    uzbekTitle: "Naba",
    verses: 40,
  },
  {
    number: 79,
    title: "Ан-Назиат",
    arabic: "ٱلنَّازِعَات",
    url: "/audio/079_an_naziat.mp3",
    transliteration: "An-Nazi'at",
    englishTitle: "Those Who Pull Out",
    uzbekTitle: "Nozi'ot",
    verses: 46,
  },
  {
    number: 80,
    title: "Абаса",
    arabic: "عَبَسَ",
    url: "/audio/080_abasa.mp3",
    transliteration: "Abasa",
    englishTitle: "He Frowned",
    uzbekTitle: "Abasa",
    verses: 42,
  },
  {
    number: 81,
    title: "Ат-Таквир",
    arabic: "ٱلتَّكْوِير",
    url: "/audio/081_at_takwir.mp3",
    transliteration: "At-Takwir",
    englishTitle: "The Overthrowing",
    uzbekTitle: "Takvir",
    verses: 29,
  },
  {
    number: 82,
    title: "Аль-Инфитар",
    arabic: "ٱلْإِنْفِطَار",
    url: "/audio/082_al_infitar.mp3",
    transliteration: "Al-Infitar",
    englishTitle: "The Cleaving",
    uzbekTitle: "Infitor",
    verses: 19,
  },
  {
    number: 83,
    title: "Аль-Мутаффифин",
    arabic: "ٱلْمُطَفِّفِين",
    url: "/audio/083_al_mutaffifin.mp3",
    transliteration: "Al-Mutaffifin",
    englishTitle: "Those Who Give Short Measure",
    uzbekTitle: "Mutaffifin",
    verses: 36,
  },
  {
    number: 84,
    title: "Аль-Иншикак",
    arabic: "ٱلْإِنْشِقَاق",
    url: "/audio/084_al_inshiqaq.mp3",
    transliteration: "Al-Inshiqaq",
    englishTitle: "The Splitting Asunder",
    uzbekTitle: "Inshiqoq",
    verses: 25,
  },
  {
    number: 85,
    title: "Аль-Бурудж",
    arabic: "ٱلْبُرُوج",
    url: "/audio/085_al_buruj.mp3",
    transliteration: "Al-Buruj",
    englishTitle: "The Stars",
    uzbekTitle: "Buruj",
    verses: 22,
  },
  {
    number: 86,
    title: "Ат-Тарик",
    arabic: "ٱلطَّارِق",
    url: "/audio/086_at_tariq.mp3",
    transliteration: "At-Tariq",
    englishTitle: "The Night-Comer",
    uzbekTitle: "Toriq",
    verses: 17,
  },
  {
    number: 87,
    title: "Аль-Аля",
    arabic: "ٱلْأَعْلَىٰ",
    url: "/audio/087_al_ala.mp3",
    transliteration: "Al-A'la",
    englishTitle: "The Most High",
    uzbekTitle: "A'lo",
    verses: 19,
  },
  {
    number: 88,
    title: "Аль-Гашия",
    arabic: "ٱلْغَاشِيَة",
    url: "/audio/088_al_ghashiya.mp3",
    transliteration: "Al-Ghashiyah",
    englishTitle: "The Overwhelming",
    uzbekTitle: "G'oshiya",
    verses: 26,
  },
  {
    number: 89,
    title: "Аль-Фаджр",
    arabic: "ٱلْفَجْر",
    url: "/audio/089_al_fajr.mp3",
    transliteration: "Al-Fajr",
    englishTitle: "The Dawn",
    uzbekTitle: "Fajr",
    verses: 30,
  },
  {
    number: 90,
    title: "Аль-Балад",
    arabic: "ٱلْبَلَد",
    url: "/audio/090_al_balad.mp3",
    transliteration: "Al-Balad",
    englishTitle: "The City",
    uzbekTitle: "Balad",
    verses: 20,
  },
  {
    number: 91,
    title: "Аш-Шамс",
    arabic: "ٱلشَّمْس",
    url: "/audio/091_ash_shams.mp3",
    transliteration: "Ash-Shams",
    englishTitle: "The Sun",
    uzbekTitle: "Shams",
    verses: 15,
  },
  {
    number: 92,
    title: "Аль-Лейль",
    arabic: "ٱللَّيْل",
    url: "/audio/092_al_layl.mp3",
    transliteration: "Al-Layl",
    englishTitle: "The Night",
    uzbekTitle: "Layl",
    verses: 21,
  },
  {
    number: 93,
    title: "Ад-Духа",
    arabic: "ٱلضُّحَىٰ",
    url: "/audio/093_ad_duha.mp3",
    transliteration: "Ad-Duha",
    englishTitle: "The Forenoon",
    uzbekTitle: "Zuho",
    verses: 11,
  },
  {
    number: 94,
    title: "Аш-Шарх",
    arabic: "ٱلشَّرْح",
    url: "/audio/094_ash_sharh.mp3",
    transliteration: "Ash-Sharh",
    englishTitle: "The Opening Forth",
    uzbekTitle: "Sharh",
    verses: 8,
  },
  {
    number: 95,
    title: "Ат-Тин",
    arabic: "ٱلتِّين",
    url: "/audio/095_at_tin.mp3",
    transliteration: "At-Tin",
    englishTitle: "The Fig",
    uzbekTitle: "Tin",
    verses: 8,
  },
  {
    number: 96,
    title: "Аль-Алак",
    arabic: "ٱلْعَلَق",
    url: "/audio/096_al_alaq.mp3",
    transliteration: "Al-Alaq",
    englishTitle: "The Clot",
    uzbekTitle: "Alaq",
    verses: 19,
  },
  {
    number: 97,
    title: "Аль-Кадр",
    arabic: "ٱلْقَدْر",
    url: "/audio/097_al_qadr.mp3",
    transliteration: "Al-Qadr",
    englishTitle: "The Night of Decree",
    uzbekTitle: "Qadr",
    verses: 5,
  },
  {
    number: 98,
    title: "Аль-Баййина",
    arabic: "ٱلْبَيِّنَة",
    url: "/audio/098_al_bayyina.mp3",
    transliteration: "Al-Bayyinah",
    englishTitle: "The Clear Evidence",
    uzbekTitle: "Bayyina",
    verses: 8,
  },
  {
    number: 99,
    title: "Аз-Зальзаля",
    arabic: "ٱلزَّلْزَلَة",
    url: "/audio/099_az_zalzala.mp3",
    transliteration: "Az-Zalzalah",
    englishTitle: "The Earthquake",
    uzbekTitle: "Zalzala",
    verses: 8,
  },
  {
    number: 100,
    title: "Аль-Адият",
    arabic: "ٱلْعَادِيَات",
    url: "/audio/100_al_adiyat.mp3",
    transliteration: "Al-Adiyat",
    englishTitle: "The Runners",
    uzbekTitle: "Odiyot",
    verses: 11,
  },
  {
    number: 101,
    title: "Аль-Кариа",
    arabic: "ٱلْقَارِعَة",
    url: "/audio/101_al_qaria.mp3",
    transliteration: "Al-Qari'ah",
    englishTitle: "The Striking Hour",
    uzbekTitle: "Qoria",
    verses: 11,
  },
  {
    number: 102,
    title: "Ат-Такасур",
    arabic: "ٱلتَّكَاثُر",
    url: "/audio/102_at_takathur.mp3",
    transliteration: "At-Takathur",
    englishTitle: "The Piling Up",
    uzbekTitle: "Takosur",
    verses: 8,
  },
  {
    number: 103,
    title: "Аль-Аср",
    arabic: "ٱلْعَصْر",
    url: "/audio/103_al_asr.mp3",
    transliteration: "Al-Asr",
    englishTitle: "The Time",
    uzbekTitle: "Asr",
    verses: 3,
  },
  {
    number: 104,
    title: "Аль-Хумаза",
    arabic: "ٱلْهُمَزَة",
    url: "/audio/104_al_humaza.mp3",
    transliteration: "Al-Humazah",
    englishTitle: "The Slanderer",
    uzbekTitle: "Humaza",
    verses: 9,
  },
  {
    number: 105,
    title: "Аль-Филь",
    arabic: "ٱلْفِيل",
    url: "/audio/105_al_fil.mp3",
    transliteration: "Al-Fil",
    englishTitle: "The Elephant",
    uzbekTitle: "Fil",
    verses: 5,
  },
  {
    number: 106,
    title: "Курайш",
    arabic: "قُرَيْش",
    url: "/audio/106_quraysh.mp3",
    transliteration: "Quraysh",
    englishTitle: "Quraysh",
    uzbekTitle: "Quraysh",
    verses: 4,
  },
  {
    number: 107,
    title: "Аль-Маун",
    arabic: "ٱلْمَاعُون",
    url: "/audio/107_al_maun.mp3",
    transliteration: "Al-Ma'un",
    englishTitle: "The Small Kindnesses",
    uzbekTitle: "Moun",
    verses: 7,
  },
  {
    number: 108,
    title: "Аль-Каусар",
    arabic: "ٱلْكَوْثَر",
    url: "/audio/108_al_kawthar.mp3",
    transliteration: "Al-Kawthar",
    englishTitle: "The River of Abundance",
    uzbekTitle: "Kavsar",
    verses: 3,
  },
  {
    number: 109,
    title: "Аль-Кафирун",
    arabic: "ٱلْكَافِرُون",
    url: "/audio/109_al_kafirun.mp3",
    transliteration: "Al-Kafirun",
    englishTitle: "The Disbelievers",
    uzbekTitle: "Kofirun",
    verses: 6,
  },
  {
    number: 110,
    title: "Ан-Наср",
    arabic: "ٱلنَّصْر",
    url: "/audio/110_an_nasr.mp3",
    transliteration: "An-Nasr",
    englishTitle: "The Help",
    uzbekTitle: "Nasr",
    verses: 3,
  },
  {
    number: 111,
    title: "Аль-Масад",
    arabic: "ٱلْمَسَد",
    url: "/audio/111_al_masad.mp3",
    transliteration: "Al-Masad",
    englishTitle: "The Palm Fiber",
    uzbekTitle: "Masad",
    verses: 5,
  },
  {
    number: 112,
    title: "Аль-Ихлас",
    arabic: "ٱلْإِخْلَاص",
    url: "/audio/112_al_ikhlas.mp3",
    transliteration: "Al-Ikhlas",
    englishTitle: "The Sincerity",
    uzbekTitle: "Ixlos",
    verses: 4,
  },
  {
    number: 113,
    title: "Аль-Фаляк",
    arabic: "ٱلْفَلَق",
    url: "/audio/113_al_falaq.mp3",
    transliteration: "Al-Falaq",
    englishTitle: "The Daybreak",
    uzbekTitle: "Falaq",
    verses: 5,
  },
  {
    number: 114,
    title: "Ан-Нас",
    arabic: "ٱلنَّاس",
    url: "/audio/114_an_nas.mp3",
    transliteration: "An-Nas",
    englishTitle: "The People",
    uzbekTitle: "Nos",
    verses: 6,
  },
]

// Функция для получения прямой ссылки на скачивание
export const getDownloadUrl = (surah: Surah) => {
  const fileId = surah.url.match(/\/file\/d\/([a-zA-Z0-9-_]+)/)?.[1]
  return fileId ? `https://drive.google.com/uc?export=download&id=${fileId}` : surah.url
}

// Функция для получения ссылки для встраивания
export const getEmbedUrl = (surah: Surah) => {
  const fileId = surah.url.match(/\/file\/d\/([a-zA-Z0-9-_]+)/)?.[1]
  return fileId ? `https://drive.google.com/file/d/${fileId}/preview` : surah.url
}

// Функция для скачивания всех сур в ZIP
export const downloadAllSurahsZip = () => {
  alert("Функция скачивания всех сур будет доступна после добавления всех файлов")
}
